server:
  port: 8199
spring:
  application:
      name: short-url-service
  datasource:
    url: jdbc:mariadb://localhost:3306/url_system
    username: root
    password: root
    driver-class-name: org.mariadb.jdbc.Driver
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      database: 1